### ISSUE TITLE
dynamic model export onnx error

### ISSUE THREAD

**Issue by CHANGErIBE** [PaddlePaddle/PLSC#102]
将PLSC的dynamic案例跑完后，将模型进行导出为onnx，然后oepncv440进行onnx模型加载报import error，尝试将输入shape由原来的[None,3,112,112]修改为[1,3,112,112]再进行export onnx 后进行onnx-simplifier，采用opencv加载模型在全连接层报出错误，不晓得是什么原因，特来咨询，谢谢

**Comment by CHANGErIBE** [comment]
情况1：paddle.static.InputSpec(shape=[None, 3, 112, 112], dtype='float32') 进行export onnx 此时如果进行onnx-simplifier会报RuntimeError: The shape of input "inputs" has dynamic size, please determine the input size manually by --input-shape xxx
故而不进行onnx-simplifier操作，直接采用oepncv440 cv::dnn::readNetFromONNX 报OpenCV(4.4.0) Error: Assertion failed (axes.getIntValue(axes.size()-1) <= dims.size()) in cv::dnn::dnn4_v20200609::ONNXImporter::populateNet, file E:\zw\opencv\sources\modules\dnn\src\onnx\onnx_importer.cpp, line 1133
基于以上的问题，初步判断为输入的shape问题
情况2：paddle.static.InputSpec(shape=[1, 3, 112, 112], dtype='float32') 进行export onnx 此时进行onnx-simplifier成功，
（1）采用oepncv440 cv::dnn::readNetFromONNX 加载sim前的模型报OpenCV(4.4.0) Error: Assertion failed (axes.getIntValue(axes.size()-1) <= dims.size()) in cv::dnn::dnn4_v20200609::ONNXImporter::populateNet, file E:\zw\opencv\sources\modules\dnn\src\onnx\onnx_importer.cpp, line 1133
（2）采用oepncv440 cv::dnn::readNetFromONNX 加载sim后的模型报
OpenCV(4.4.0) Error: Assertion failed (!bias || (blobs.size() == 2 && (size_t)numOutput == blobs[1].total())) in cv::dnn::FullyConnectedLayerImpl::FullyConnectedLayerImpl, file E:\zw\opencv\sources\modules\dnn\src\layers\fully_connected_layer.cpp, line 90

**Comment by CHANGErIBE** [comment]
export sh:
python tools/export.py \
    --is_static False \
    --export_type onnx \
    --backbone FresResNet50 \
    --embedding_size 512 \
    --checkpoint_dir MS1M_v3_arcface_dynamic_0.1/FresResNet50/24 \
    --output_dir MS1M_v3_arcface_dynamic_0.1/FresResNet50/exported_model
代码没做任何修改就是下载官网提供的数据训练的模型，然后模型导出就出了以上这个问题

**Comment by GuoxiaWang** [comment]
@CHANGErIBE

**Comment by GuoxiaWang** [comment]
@CHANGErIBE 

用最新的 paddle2onnx 包，用 develop 编译，导出来的直接能在 opencv 中运行，不需要 onnx-simplifier 进行简化
```
 pip uninstall paddle2onnx

 git clone https://github.com/PaddlePaddle/Paddle2ONNX.git
 cd Paddle2ONNX
 python setup.py install
```

如果有继续使用 onnx-simplifier 的需求，并遇到相关问题，可以去 onnx-simplifier 仓库中给他们提 issue。

**Comment by CHANGErIBE** [comment]
@GuoxiaWang 
按照所提供的方法，生成onnx模型后用opencv440加载模型时报出：
OpenCV(4.4.0) Error: Backtrace (Can't infer a dim denoted by -1) in cv::dnn::computeShapeByReshapeMask, file E:\zw\opencv\sources\modules\dnn\src\layers\reshape_layer.cpp, line 154

**Comment by CHANGErIBE** [comment]
因为按照PLSC默认的dynamic案例训练出来的模型保存在/MS1M_v3_arcface_dynamic_0.1/FresResNet50/24/下，有很多个文件，我这边首先采用PLSC提供的export_dynamic.sh将这些文件合并成.pdiparams 和 .pdmodel文件，然后用paddle2onnx 生成对应的onnx模型，再在windows端用opencv加载报出以上问题

**Comment by GuoxiaWang** [comment]
```
mkdir -p models

wget https://plsc.bj.bcebos.com/pretrained_model/MS1M_v3_arcface_Res50_dynamic_0.1_NHWC_FP16_v2.2.tgz -P models/
tar -xzf models/MS1M_v3_arcface_Res50_dynamic_0.1_NHWC_FP16_v2.2.tgz -C models/

python tools/export.py --is_static False --export_type onnx --backbone FresResNet50 --embedding_size 512 --checkpoint_dir models/MS1M_v3_arcface_Res50_dynamic_0.1_NHWC_FP16_v2.2/FresResNet50/best_model/cfp_fp/ --output_dir models/MS1M_v3_arcface_Res50_dynamic_0.1_NHWC_FP16_v2.2_infer
```


测试代码
```
import numpy as np                                     
import cv2

net = cv2.dnn.readNetFromONNX("models/MS1M_v3_arcface_Res50_dynamic_0.1_NHWC_FP16_v2.2_infer/FresResNet50.onnx")

image = np.random.uniform(-1, 1, size=(1, 3, 112, 112))
net.setInput(image)
outNames = net.getUnconnectedOutLayersNames()                    
outs = net.forward(outNames)                                                                                                                               
print(outs)
```

你试试看？

**Comment by CHANGErIBE** [comment]
我将opencv版本更新到4.5后，问题就解决了，谢谢
