### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'data_format'

### ISSUE THREAD

**Issue by wenhwu** [PaddlePaddle/PLSC#109]
https://github.com/PaddlePaddle/PLSC/blob/731eb3f5952f8f56e6d41f6bd4b9d465a63cd582/dynamic/backbones/mobilefacenet.py#L45

`nn.PReLU`类定义的初始化参数里是没有`data_format`的，但是`mobilefacenet.py`中大量的`nn.PReLU`都有`data_format`参数，在运行时就会报`TypeError: __init__() got an unexpected keyword argument 'data_format'`的错，请问这是什么情况呢？

谢谢

**Comment by GuoxiaWang** [comment]
@wenhwu 请安装  paddle 2.2 分支稳定版本

**Comment by wenhwu** [comment]
@GuoxiaWang，明白了，谢谢您的及时回复！
