### ISSUE TITLE
输出模型是如何设计的？

### ISSUE THREAD

**Issue by geoexploring** [PaddlePaddle/PLSC#110]
我基于`MS1M_v3_arcface_MobileFaceNet_128_0.1`跑出了模型，输出模型格式如下图：

![Screenshot_1](https://user-images.githubusercontent.com/58645709/158548831-4693163c-e062-4786-954b-afa0ec7b885d.png)

![Screenshot_2](https://user-images.githubusercontent.com/58645709/158548841-231f9d39-0fa0-42ac-a5a5-172cf0015864.png)

请问是不是因为验证时，是三个数据集（类别不一样），所以输出三个模型？
另外请问为什么输出结果是大量的分散文件，而不是类似`FresResNet50.pdiparams`这样的一个文件，或者说可以将以上的分散文件合并吗？

谢谢！

**Comment by geoexploring** [comment]
@GuoxiaWang ，谢谢您的快速回复！

请问如果是分散文件，在inference时应该怎么写inference命令行呢？比如类似如下的操作：
```
python tools/inference.py \
    --export_type paddle \
    --model_file MS1M_v3_arcface_static_128_fp16_0.1/FresResNet50/exported_model/FresResNet50.pdmodel \
    --params_file MS1M_v3_arcface_static_128_fp16_0.1/FresResNet50/exported_model/FresResNet50.pdiparams \
    --image_path MS1M_v3/images/00000001.jpg

```

谢谢！

**Comment by GuoxiaWang** [comment]
> @GuoxiaWang ，谢谢您的快速回复！
> 
> 请问如果是分散文件，在inference时应该怎么写inference命令行呢？比如类似如下的操作：
> 
> ```
> python tools/inference.py \
>     --export_type paddle \
>     --model_file MS1M_v3_arcface_static_128_fp16_0.1/FresResNet50/exported_model/FresResNet50.pdmodel \
>     --params_file MS1M_v3_arcface_static_128_fp16_0.1/FresResNet50/exported_model/FresResNet50.pdiparams \
>     --image_path MS1M_v3/images/00000001.jpg
> ```
> 
> 谢谢！

inference 首先需要导出模型，通过 scripts/export_dynamic.sh 将分散的 checkpoint 文件 导出 paddle 的 inference model 或者 onnx。

然后再调用 tools/inference.py

**Comment by geoexploring** [comment]
@GuoxiaWang ，大佬给力！
