### ISSUE TITLE
inference.py推理结果的含义是？

### ISSUE THREAD

**Issue by geoexploring** [PaddlePaddle/PLSC#111]
`inference.py`中的主要函数是：

```python
def paddle_inference(args):
    import paddle.inference as paddle_infer

    config = paddle_infer.Config(args.model_file, args.params_file)
    predictor = paddle_infer.create_predictor(config)

    input_names = predictor.get_input_names()
    input_handle = predictor.get_input_handle(input_names[0])

    img = cv2.imread(args.image_path)
    # normalize to mean 0.5, std 0.5
    img = (img - 127.5) * 0.00784313725
    # BGR2RGB
    img = img[:, :, ::-1]
    img = img.transpose((2, 0, 1))
    img = np.expand_dims(img, 0)
    img = img.astype('float32')

    input_handle.copy_from_cpu(img)

    predictor.run()

    output_names = predictor.get_output_names()
    output_handle = predictor.get_output_handle(output_names[0])
    output_data = output_handle.copy_to_cpu()

    print('paddle inference result: ', output_data.shape)
```

基于MS1M_v3数据集训练出来的模型，去推理`MS1M_v3\images\00000001.jpg`，根据`paddle_inference`函数，推理结果是类似` (1, 128)`的数组，这个数组的含义是什么呢？输出结果不应该是类似单个类别一样的数字吗（比如0或者其他数字）

谢谢！

**Comment by GuoxiaWang** [comment]
@geoexploring 

只是给出一个推理示例，这块需要用户结合自己需要的场景去使用。
换句话说，只是给出一个 paddle inference model 推理得到一个 feature 的例子以及 onnx model 推理得到一个 feature 的例子

**Comment by geoexploring** [comment]
@GuoxiaWang , 谢谢您的快速回复！

如果是做人脸识别，数据集是MS1M_v3，请问推理代码的具体实现可以参考`PLSC\tools\validation.py`的部分代码吗？
又比如：

> 人脸数据库有10000个人，20000张人脸图片。现在判断某一张人脸图片是10000个人中的哪个人，其代码运行的逻辑是：
> 1. PLSC输出的人脸嵌入向量维度是128，则对于20000张图形成的特征矩阵形状是a，a.shape=(128, 20000);
> 2. 对于测试的该张图片，经过CNN得到嵌入向量b，b.shape=(1, 128)；
> 3. 把测试图片的嵌入向量b与特征矩阵a做矩阵运算，得到结果c，c.shape=(1,20000)；
> 4. 根据c，判断测试图片是哪个人。

我是一个刚入人脸识别坑的小白，请问对于人脸识别场景，`inference.py`的设计可以是这样的逻辑吗？

**Comment by GuoxiaWang** [comment]
@geoexploring 
不是，inference.py 只是给出了示例，给定一张人脸图像，经过特征提取器得到 b。

通常情况下，人脸识别部署相对要复杂一些，提前离线建立查询库，建立好索引，然后给定一张要查询的人脸图像，经过特征提取器得到一个特征，然后从这个数据库中查询。

简单的过程，可以参照 https://github.com/PaddlePaddle/PLSC#10-demo

**Comment by geoexploring** [comment]
@GuoxiaWang , 明白了，谢谢解答！

**Comment by geoexploring** [comment]
@GuoxiaWang ，我按照您上面给出的https://github.com/PaddlePaddle/PLSC#10-demo，

发现在`images\Friends\query`中的`friends1.jpg`和`friends2.jpg`是能正常运行的，结果如下：

![friends1](https://user-images.githubusercontent.com/58645709/158772389-7baa6ace-d8af-4616-9eb6-ccc02e4ae57d.jpg)
![friends2](https://user-images.githubusercontent.com/58645709/158772413-33a9d3c0-27ed-42f5-8ded-39254cd7ca59.jpg)


但是`images\Friends\query`中的`Rachel.png`却无法检测，输出结果是空的：
![Rachel](https://user-images.githubusercontent.com/58645709/158772457-7c38a404-b1a3-43b1-b02b-c79fa4162999.png)

https://github.com/PaddlePaddle/PLSC/blob/731eb3f5952f8f56e6d41f6bd4b9d465a63cd582/tools/test_recognition.py#L609

即对于`Rachel.png`这张图，`box_list`的值为`[ ]`。

请问这样合理吗？
谢谢！

**Comment by GuoxiaWang** [comment]
@geoexploring  
可能人脸占比太小了，人脸检测没有检测到人脸

**Comment by geoexploring** [comment]
@GuoxiaWang 

```python
    def postprocess(self, np_boxes):
        expect_boxes = (np_boxes[:, 1] > self.thresh) & (np_boxes[:, 0] > -1)
        return np_boxes[expect_boxes, :]

    def predict(self, img):
        inputs = self.preprocess(img)
        for input_name in self.input_names:
            input_tensor = self.predictor.get_input_handle(input_name)
            input_tensor.copy_from_cpu(inputs[input_name])
        self.predictor.run()
        output_tensor = self.predictor.get_output_handle(self.output_names[0])
        np_boxes = output_tensor.copy_to_cpu()
        # boxes_num = self.detector.get_output_handle(self.detector_output_names[1])
        # np_boxes_num = boxes_num.copy_to_cpu()
        box_list = self.postprocess(np_boxes)
        return box_list
```

在输入`Rachel.png`时，导致`box_list`的值为`[ ]`是因为上面的`postprocess`函数，

而在输入`postprocess`函数前，np_boxes的值是：
![Screenshot_1](https://user-images.githubusercontent.com/58645709/158776996-0ce314d3-a441-47f1-ba36-6fc25b403344.png)

请问`np_boxes`的值是合理的吗？

谢谢

**Comment by GuoxiaWang** [comment]
@geoexploring 
你可以看看是不是被人脸检测的分数阈值过滤掉了

**Comment by geoexploring** [comment]
@GuoxiaWang 

确实是过滤掉了，我把`det_thresh`改成0.0，输出结果是：

![Rachel](https://user-images.githubusercontent.com/58645709/158781254-fad3759c-6b39-4422-951b-108ebd9a6849.png)

这就是您上面提到的类似问题：人脸占比太大导致人脸检测效果不好。

我明白了，谢谢！
