### ISSUE TITLE
Lr过小时会导致Loss为nan

### ISSUE THREAD

**Issue by geoexploring** [PaddlePaddle/PLSC#112]
在训练自定义的数据集时，发现`Lr`过小时会导致`Loss`为nan，特别是当`Lr`缩小为原来的十分之一时（比如`0.025`变为`0.0025`，`0.1`变化`0.01`），都会导致`Loss`变化nan，然后导致训练中断，具体的训练日志请见：

[0.01_training.log](https://github.com/PaddlePaddle/PLSC/files/8338125/0.01_training.log)
[0.1_training.log](https://github.com/PaddlePaddle/PLSC/files/8338126/0.1_training.log)
[0.2_training.log](https://github.com/PaddlePaddle/PLSC/files/8338127/0.2_training.log)

请问该如何解决呢？

另外，在验证时：

- `Loss`在刚开始下降到`15`左右之后，就很难下降；
- 精度指标`XNorm`在飞快下降(比如从`64288.505847`降到`0.017919`)；
- 而精度指标`Accuracy-Highest`一直徘徊在`0.50903`左右；

我是一个刚入门人脸识别的小白，不确定这是什么情况，还请给出一些建议

感谢！

**Comment by GuoxiaWang** [comment]
@geoexploring 

看了一下，压根没学到东西。目前看不出什么问题，我看你是用单卡训的，可以从以下几个步骤进行排查。
（1）把 sample_ratio: 0.1 改成 sample_ratio: 1.0 试试， 先排除 PartialFC 的问题

此外，你用的是什么 paddle 版本，推荐使用稳定的 release 2.2 版本

**Comment by geoexploring** [comment]
@GuoxiaWang ，感谢您的及时回复。

我是在百度的AI Studio上训练的，Paddle的版本是`paddlepaddle-gpu 2.2.2.post101`。

按照您的建议，将`sample_ratio`改成`1.0`后，仍然会出现:
>`Lr`过小时会导致`Loss`为nan，特别是当`Lr`缩小为原来的十分之一时（比如`0.025`变为`0.0025`，`0.1`变化`0.01`），都会导致`Loss`变化nan；
>在验证集上的评估后的结果也和上述相同。

这个错误的规律倒是很明显，
谢谢！

**Comment by GuoxiaWang** [comment]
你的数据集是可见的吗？我可以拿你的数据以及你的配置复现一下

**Comment by geoexploring** [comment]
@GuoxiaWang , 谢谢您！

这个涉及到公司业务上的数据，而且数据组织很繁琐，可能会耽搁您很长时间，我再研究研究。

万分感谢！

**Comment by GuoxiaWang** [comment]
@geoexploring 可以先拿公开数据集用你的配置来试试看看，如果公开集也有问题，那就是代码写得有问题了，如果公开集没问题，那就是你那边数据处理有问题

**Comment by geoexploring** [comment]
@GuoxiaWang ，谢谢您！

我们那个数据集属于另一种类型的问题了，目前还没有公开数据集。谢谢您的建议，我再看看网络架构和数据加载方面有没有啥问题。

谢谢！

**Comment by geoexploring** [comment]
@GuoxiaWang 

发现新特点：当用FP16训练时，不会出现上述的训练中途Loss变为nan的情况，但是会经常弹出信息`Found inf or nan of distributed parameter, dtype is paddle.float16；Found inf or nan, current scale is: 13824.0, decrease to: 13824.0*0.5`，并且 Loss下降速度相比FP32会慢很多。请问这是什么原因呢？

**Comment by GuoxiaWang** [comment]
@geoexploring 

> Found inf or nan of distributed parameter, dtype is paddle.float16；Found inf or nan, current scale is: 13824.0, decrease to: 13824.0*0.5

这个是正常的，我故意打印的，使用 FP16 的时候是有一个叫做 loss scaling 的东西，上面这句话是在当模型并行的 FC 中计算时，梯度出 nan/inf 了，这时候会跳过当前步的更新，同时  loss scaling  缩小一倍，继续走下一个 step，当2000步没出现 nan/inf 了，loss scaling 又调大一倍。

**Comment by geoexploring** [comment]
@GuoxiaWang , 谢谢您的快速回复！

这确实是一个不错的设计，其他问题我发邮件咨询您。谢谢！
